spring:
  application:
    name: event-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/event_manager?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate 
    show-sql: false